debug: true

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db.dpjcotkkgyxfhxdolptf.supabase.co:5432/postgres?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${DB_PASSWORD:AqTZ2vyBEhs9X22K}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      connection-timeout: 20000
      connection-init-sql: "SELECT 1"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: ${SPRING_FLYWAY_URL:${spring.datasource.url}}
    user: ${SPRING_FLYWAY_USER:${spring.datasource.username}}
    password: ${SPRING_FLYWAY_PASSWORD:${spring.datasource.password}}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:citrus-humorous-bone-47657.db.redis.io}
      port: ${SPRING_DATA_REDIS_PORT:11805}
      password: ${SPRING_DATA_REDIS_PASSWORD:6KqqMhC6hTRru0X6TdmbJfSGIACWaJoF}
      username: ${SPRING_DATA_REDIS_USERNAME:default}

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    org.hibernate: DEBUG
    com.voum: DEBUG

voum:
  redis:
    enabled: true

app:
  storage:
    type: r2
    r2:
      account-id: ${R2_ACCOUNT_ID:c506f5824f4bbf1cc9d2cc7863ddb3a9}
      access-key-id: ${R2_ACCESS_KEY_ID:5eea1844410770987ccb750f061ecbda}
      secret-access-key: ${R2_SECRET_ACCESS_KEY:c3f6aceca37206d072f79979b7453163ea9c46df2a004a6f8baaa714fac53d48}
      bucket-name: ${R2_BUCKET_NAME:voum-data}
      public-domain: ${R2_PUBLIC_DOMAIN:https://c506f5824f4bbf1cc9d2cc7863ddb3a9.r2.cloudflarestorage.com}
